# Generated by Django 5.2.4 on 2025-09-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cupon",
            fields=[
                ("idCupon", models.AutoField(primary_key=True, serialize=False)),
                ("descuentoCupon", models.IntegerField()),
                ("codigoCupon", models.CharField()),
                ("estadoCupon", models.BooleanField()),
                ("fechaVencimientoCupon", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idProducto", models.AutoField(primary_key=True, serialize=False)),
                ("nombreProducto", models.CharField(max_length=100)),
                ("tipoProducto", models.CharField(max_length=50)),
                ("marcaProducto", models.CharField(max_length=50)),
                ("cantidadDeProducto", models.IntegerField()),
                ("fechaVencimientoProducto", models.DateField()),
                ("precioDeProducto", models.FloatField()),
                ("imagenProducto", models.ImageField(upload_to="productos/")),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("idUsuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombreCompletoUsuario", models.CharField()),
                ("correoUsuario", models.CharField()),
                ("contraseñaUsuario", models.CharField()),
                (
                    "tipoUsuario",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("admin", "Administrador")],
                        default="cliente",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("idReserva", models.AutoField(primary_key=True, serialize=False)),
                ("fechaReserva", models.DateField(auto_now_add=True)),
                ("horaReserva", models.TimeField(auto_now_add=True)),
                ("precioFinalReserva", models.FloatField(default=0.0)),
                ("numeroPersonasReserva", models.IntegerField()),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True, related_name="reservas", to="Sesion.producto"
                    ),
                ),
                (
                    "reservaCupon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sesion.cupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("idSesion", models.AutoField(primary_key=True, serialize=False)),
                ("nombreSesion", models.CharField()),
                ("categoriaSesion", models.CharField()),
                ("descripcionSesion", models.TextField()),
                ("imagenSesion", models.ImageField(upload_to="sesiones/")),
                ("precioSesion", models.FloatField()),
                ("duracionSesion", models.IntegerField()),
                ("horaSesion", models.CharField()),
                ("disponibleSesion", models.BooleanField()),
                (
                    "reservaSesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesion",
                        to="Sesion.reserva",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reserva",
            name="sesiones",
            field=models.ManyToManyField(
                blank=True, related_name="reservas", to="Sesion.sesion"
            ),
        ),
        migrations.CreateModel(
            name="Reseña",
            fields=[
                ("idReseña", models.AutoField(primary_key=True, serialize=False)),
                ("comentarioReseña", models.TextField()),
                ("calificacionReseña", models.IntegerField()),
                ("fechaReseña", models.DateField(auto_now_add=True)),
                (
                    "reseñaSesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseñas",
                        to="Sesion.sesion",
                    ),
                ),
                (
                    "reseñaUsuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseñas",
                        to="Sesion.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="Sesion.usuario",
            ),
        ),
    ]
