# Generated by Django 5.2.4 on 2025-08-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("idReserva", models.IntegerField(primary_key=True, serialize=False)),
                ("fechaReserva", models.DateField()),
                ("horaReserva", models.CharField()),
                ("precioFinalReserva", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("idSesion", models.IntegerField(primary_key=True, serialize=False)),
                ("nombreSesion", models.CharField()),
                ("categoriaSesion", models.CharField()),
                ("descripcionSesion", models.TextField()),
                ("precioSesion", models.FloatField()),
                ("imagenSesion", models.CharField()),
                ("duracionSesion", models.IntegerField()),
                ("horaSesion", models.CharField()),
                ("disponibleSesion", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Reseña",
            fields=[
                ("idReseña", models.IntegerField(primary_key=True, serialize=False)),
                ("comentarioReseña", models.TextField()),
                ("calificacionResñea", models.FloatField()),
                ("fechaReseña", models.DateField()),
                (
                    "reseñaSesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseña",
                        to="Sesion.sesion",
                    ),
                ),
            ],
        ),
    ]
