# Generated by Django 5.2.5 on 2025-08-23 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('idCupon', models.IntegerField(primary_key=True, serialize=False)),
                ('descuentoCupon', models.IntegerField()),
                ('codigoCupon', models.CharField()),
                ('estadoCupon', models.BooleanField()),
                ('fechaVencimientoCupon', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCompletoUsuario', models.CharField()),
                ('correoUsuario', models.CharField()),
                ('contraseñaUsuario', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.CharField()),
                ('precioFinalReserva', models.FloatField()),
                ('reservaCupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sesion.cupon')),
                ('reservasUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Sesion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoProducto', models.CharField()),
                ('cantidadDeProducto', models.IntegerField()),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('marcaProducto', models.CharField()),
                ('fechaVencimientoProducto', models.DateField()),
                ('productoReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Sesion.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idSesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSesion', models.CharField()),
                ('categoriaSesion', models.CharField()),
                ('descripcionSesion', models.TextField()),
                ('imagenSesion', models.ImageField(blank=True, null=True, upload_to='sesiones/')),
                ('precioSesion', models.FloatField()),
                ('duracionSesion', models.IntegerField()),
                ('horaSesion', models.CharField()),
                ('disponibleSesion', models.BooleanField()),
                ('sesionesReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Sesion.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('idReseña', models.IntegerField(primary_key=True, serialize=False)),
                ('comentarioReseña', models.TextField()),
                ('calificacionReseña', models.FloatField()),
                ('fechaReseña', models.DateField()),
                ('reseñaSesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='Sesion.sesion')),
                ('reseñaUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='Sesion.usuario')),
            ],
        ),
    ]
