# Generated by Django 5.2.4 on 2025-09-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesion",
            name="reservaSesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesion",
                to="Sesion.reserva",
            ),
        ),
    ]
