# Generated by Django 5.2.4 on 2025-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("idUsuario", models.IntegerField(primary_key=True, serialize=False)),
                ("nombreCompletoUsuario", models.CharField()),
                ("correoUsuario", models.CharField()),
                ("contraseñaUsuario", models.CharField()),
            ],
        ),
    ]
