# Generated by Django 5.2.4 on 2025-09-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0002_alter_sesion_reservasesion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="numeroPersonasReserva",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
