# Generated by Django 5.2.4 on 2025-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0002_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupon",
            fields=[
                ("idCupon", models.IntegerField(primary_key=True, serialize=False)),
                ("descuentoCupon", models.IntegerField()),
                ("codigoCupon", models.CharField()),
                ("estadoCupon", models.BooleanField()),
                ("fechaVencimientoCupon", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("idProducto", models.IntegerField(primary_key=True, serialize=False)),
                ("tipoProducto", models.CharField()),
                ("cantidadDeProducto", models.IntegerField()),
                ("marcaProducto", models.CharField()),
                ("fechaVencimientoProducto", models.DateField()),
            ],
        ),
    ]
