# Generated by Django 5.2.4 on 2025-08-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0003_cupon_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sesion",
            name="imagenSesion",
        ),
        migrations.AddField(
            model_name="producto",
            name="productoReserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="Sesion.reserva",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="reservaCupon",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Sesion.cupon",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="reservasUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="Sesion.usuario",
            ),
        ),
        migrations.AddField(
            model_name="reseña",
            name="reseñaUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reseñas",
                to="Sesion.usuario",
            ),
        ),
        migrations.AddField(
            model_name="sesion",
            name="sesionesReserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="Sesion.sesion",
            ),
        ),
        migrations.AlterField(
            model_name="reseña",
            name="reseñaSesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reseñas",
                to="Sesion.sesion",
            ),
        ),
    ]
