# Generated by Django 5.2.4 on 2025-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0003_alter_reserva_numeropersonasreserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[("activa", "Activa"), ("enviada", "Enviada")],
                default="activa",
                max_length=20,
            ),
        ),
    ]
