# Generated by Django 5.2.4 on 2025-08-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0004_remove_sesion_imagensesion_producto_productoreserva_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reseña",
            old_name="calificacionResñea",
            new_name="calificacionReseña",
        ),
    ]
