# Generated by Django 5.2.4 on 2025-09-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0004_reserva_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sesion",
            name="disponibleSesion",
        ),
    ]
