# Generated by Django 5.2.4 on 2025-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0004_remove_sesion_imagensesion_producto_productoreserva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagenProducto",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="sesion",
            name="imagenSesion",
            field=models.ImageField(blank=True, null=True, upload_to="sesiones/"),
        ),
    ]
