# Generated by Django 5.2.7 on 2025-11-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0005_remove_sesion_disponiblesesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='precioSesion',
            field=models.IntegerField(),
        ),
    ]
