# Generated by Django 5.2.7 on 2025-11-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0006_alter_sesion_preciosesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioDeProducto',
            field=models.IntegerField(),
        ),
    ]
