# Generated by Django 5.2.4 on 2025-09-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0007_producto_preciodeproducto_carrito_itemcarrito"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="nombreProducto",
            field=models.CharField(blank=True, null=True),
        ),
    ]
