# Generated by Django 5.2.4 on 2025-09-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0008_producto_nombreproducto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reseña",
            old_name="reseñaUser",
            new_name="reseñaUsuario",
        ),
        migrations.AlterField(
            model_name="reseña",
            name="calificacionReseña",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reseña",
            name="fechaReseña",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reseña",
            name="idReseña",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
