# Generated by Django 5.2.4 on 2025-09-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0009_rename_reseñauser_reseña_reseñausuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupon",
            name="idCupon",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="idProducto",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="idReserva",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="idSesion",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idUsuario",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
