# Generated by Django 5.2.4 on 2025-09-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0010_alter_cupon_idcupon_alter_producto_idproducto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="numeroPersonasReserva",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="sesionesReserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="Sesion.reserva",
            ),
        ),
    ]
