# Generated by Django 5.2.4 on 2025-09-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0011_reserva_numeropersonasreserva_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reserva",
            old_name="reservasUser",
            new_name="usuario",
        ),
        migrations.RemoveField(
            model_name="sesion",
            name="sesionesReserva",
        ),
        migrations.AddField(
            model_name="itemcarrito",
            name="sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Sesion.sesion",
            ),
        ),
        migrations.AddField(
            model_name="sesion",
            name="reserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesiones",
                to="Sesion.reserva",
            ),
        ),
        migrations.AlterField(
            model_name="carrito",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrito",
                to="Sesion.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="itemcarrito",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Sesion.producto",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="fechaReserva",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="horaReserva",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="ItemReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("precioUnitario", models.FloatField()),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sesion.producto",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Sesion.reserva",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Sesion.sesion",
                    ),
                ),
            ],
        ),
    ]
