# Generated by Django 5.2.5 on 2025-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0011_reserva_numeropersonasreserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=10),
        ),
    ]
