# Generated by Django 5.2.4 on 2025-09-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0012_rename_reservasuser_reserva_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemreserva",
            old_name="cantidad",
            new_name="cantidadItem",
        ),
        migrations.RenameField(
            model_name="itemreserva",
            old_name="precioUnitario",
            new_name="precioUnitarioItem",
        ),
        migrations.RenameField(
            model_name="itemreserva",
            old_name="producto",
            new_name="productoItem",
        ),
        migrations.RenameField(
            model_name="itemreserva",
            old_name="reserva",
            new_name="reservaItem",
        ),
        migrations.RenameField(
            model_name="itemreserva",
            old_name="sesion",
            new_name="sesionItem",
        ),
        migrations.RenameField(
            model_name="sesion",
            old_name="reserva",
            new_name="reservaSesion",
        ),
    ]
