# Generated by Django 5.2.5 on 2025-09-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0012_usuario_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioDeProducto',
            field=models.FloatField(),
        ),
    ]
