# Generated by Django 5.2.4 on 2025-09-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0013_rename_cantidad_itemreserva_cantidaditem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesion",
            name="reservaSesion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesion",
                to="Sesion.reserva",
            ),
        ),
    ]
