# Generated by Django 5.2.5 on 2025-09-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0013_alter_producto_preciodeproducto'),
        ('Sesion', '0014_alter_sesion_reservasesion'),
    ]

    operations = [
    ]
