# Generated by Django 5.2.4 on 2025-09-13 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sesion", "0015_merge_20250912_1847"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcarrito",
            name="carrito",
        ),
        migrations.RemoveField(
            model_name="itemcarrito",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="itemcarrito",
            name="sesion",
        ),
        migrations.RemoveField(
            model_name="itemreserva",
            name="productoItem",
        ),
        migrations.RemoveField(
            model_name="itemreserva",
            name="reservaItem",
        ),
        migrations.RemoveField(
            model_name="itemreserva",
            name="sesionItem",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="productoReserva",
        ),
        migrations.AddField(
            model_name="reserva",
            name="productos",
            field=models.ManyToManyField(
                blank=True, related_name="reservas", to="Sesion.producto"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="sesiones",
            field=models.ManyToManyField(
                blank=True, related_name="reservas", to="Sesion.sesion"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fechaVencimientoProducto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="marcaProducto",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombreProducto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipoProducto",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="precioFinalReserva",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="reservaSesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesion",
                to="Sesion.reserva",
            ),
        ),
        migrations.DeleteModel(
            name="Carrito",
        ),
        migrations.DeleteModel(
            name="ItemCarrito",
        ),
        migrations.DeleteModel(
            name="ItemReserva",
        ),
    ]
